Fatal error: exception Failure("Can not use return outside of function.")