Fatal error: exception Failure("Cannot call break outside of iterative loop")